# Generated by Django 4.0.2 on 2022-02-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='user-default.jpg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
