# Generated by Django 4.0.2 on 2022-02-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='user-default.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
